version: "2"
services:
  node:
    image: "node:14"
    user: "node"
    working_dir: /home/node/app
#    environment:
#      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "8300:3000"
    command: "yarn start"
